### ISSUE TITLE
Support Needed for AngularJs

### ISSUE THREAD

**Issue by anil1712** [sinch/sinch-js-rtc#16]
Hi,
First of all Sinch is having very rich features related to calling and messaging with great documentation but I am working on AngularJs project so I needed to integrate on that project.

I integrated the logical part like creting SinchClient and alling respective methods but got stuck on manipulatuing HTML using jQuey to show call button or invoke any listeners while clicking on that button.

@magnuslundstedt Please give me any solution to integrate the same sdk into my angularjs project.

Thanks,

**Comment by yusandman** [comment]
Hi!  Function "sendMessage" fire twice:

var vm = this;

            vm.usernameToMessage = vm.textMessage = '';

            var message, messageClient = null;

            var incomingMessageListener = {
                onIncomingMessage: function (incomingMessage) {
                    console.log(incomingMessage);
                    $('div#messages').append("<div>" + incomingMessage.textBody + "</div>")
                },
                onMessageDelivered: function (incomingMessage) {
                    console.log(incomingMessage);
                }
            };

            user.sinchClient.startActiveConnection();
            messageClient = user.sinchClient.getMessageClient();
            messageClient.addEventListener(incomingMessageListener);

            vm.sendMessage = function () {
                message = messageClient.newMessage(vm.usernameToMessage, vm.textMessage);
                messageClient.send(message);
                message = null;
            };

Do you know why?
