### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by josefrichter** [sinch/sinch-js-rtc#2]
npm ERR! Failed at the wrtc@0.0.55 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build

here's the npm-debug.log it generated: https://gist.github.com/josefrichter/063240e51326d7cd307b

any suggestions?

**Comment by josefrichter** [comment]
found a workaround, not solution:
- use node 0.12.7
- download MacOSX10.10.sdk from here https://github.com/phracker/MacOSX-SDKs/releases
- put the SDK into Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs

based on https://github.com/js-platform/node-webrtc/issues/235#issuecomment-152447773

**Comment by cahlbin** [comment]
Thanks @josefrichter for the suggestion for a workaround. Closing.
