### ISSUE TITLE
Audio or video calling from Web to Android/IOS support

### ISSUE THREAD

**Issue by yadagiribalemula** [sinch/sinch-js-rtc#29]
I have take Javascript SDK 1.4.5, and Android SDK 3.17.4 
Implemented both android app and javascipt web app
1) Working great when checked web-web
2) Able to make call from android, also receiving from javascipt 
using 

CallClient callClient = sinchClient.getCallClient();
Call call = callClient.callUser("<remote user id>");

But unable to make call from Web application to android. I tried all possible scenarios like server authentication but not getting call.
Received TIMEOUT error.

Any help..? Is Web to App calling supporting now?

**Comment by zhuxiaoyu88** [comment]
hi @yadagiribalemula how did you solve it ? I'm facing this issue right now.
