### ISSUE TITLE
react native support?

### ISSUE THREAD

**Issue by josefrichter** [sinch/sinch-js-rtc#3]
Trying to implement JS SDK into a React Native app. Running into 'requiring unknown module pubnub' error. 

From what I googled, it seems that PubNub package simply doesn't work with React Native because of various web sockets problems. It seems though, that Firebase and RealtimeFramework guys were able to resolve similar issues, see e.g. https://groups.google.com/forum/#!topic/firebase-talk/aoPNvQQsVUE

Is anybody at Sinch working on React Native support, please? Or can you suggest some workarounds?

**Comment by abeaclark** [comment]
Having the same problem. Can't figure out how to get past it.

**Comment by Wolke** [comment]
I need it

**Comment by spacedsweden** [comment]
Hi. 
Even if pubnub would start to work it would still be an issue with WebRTC, sinchRTC js wont support ReactNative. If we would add support for it it would be a bridge to the native SDKs,

**Comment by shukerullah** [comment]
Any news on this?

**Comment by EduardJS** [comment]
This is really a bummer. We’ve used Sinch for our cross platform product, and now that we want to go away from iOS and Android towards React Native, we found ourselves trapped eith no other Solution.

As it seems now, the only alternative is to move everything go VoxImplant as they seem to have managed sorting out the issue.

**Comment by EduardJS** [comment]
Have to add, it’s very weird such a big service like Sinch does not put interest internally into such a big ecosystem like react native.

**Comment by VbhuvanReddy** [comment]
Has anyone tried to link android SDK to React Native.

**Comment by marquesjordan** [comment]
Has anybody figured out how to create a bridge for Sinch and React-Native?
