### ISSUE TITLE
WebRTC error when answering a call in Chrome 52

### ISSUE THREAD

**Issue by gabro** [sinch/sinch-js-rtc#7]
I have a web-application that performs app-to-app calling with an iOS client.

Since updating to Chrome 52, if I start a call from the web client, as soon as the iOS client answers the call, I get this error on the console and the call cannot be established.

> Error setting local Description, message: OperationError: Failed to set local offer sdp: Failed to push down transport description: Local fingerprint does not match identity. Expected: sha-256 90:73:99:BD:21:80:12:C1:19:2A:21:7D:48:02:FF:A1:97:BF:1F:6A:3C:54:26:46:D5:D5:84:80:11:6F:1D:16 Got: sha-256 43:DC:19:03:70:C1:45:E5:30:AE:03:F3:31:71:45:14:68:CE:A9:A7:4D:CB:D2:CE:AF:C3:84:4F:94:45:AE:B9

The exact same process works just fine in Chrome <= 51.

Is this a known bug? Any workaround?

**Comment by gabro** [comment]
Ok, the issue seems to be with ECDSA certificates (which Chrome uses by default since version 52)

Setting `chrome://flags/#enable-webrtc-ecdsa` to `Disabled` fixes the issue.

Any chance to getting this fixed?

**Comment by slavasav** [comment]
Hi,
Thanks for your report. We are aware of this change and will fix this in the next release.

**Comment by gabro** [comment]
Hi @slavasav, thanks for the prompt response.
When is the next release scheduled?
My users are completely unable to perform videocalls right now, so this is extremely critical.

Thanks

**Comment by slavasav** [comment]
Expecting this to go out next 1-2 weeks.

**Comment by gabro** [comment]
Ok, thanks.

**Comment by lucacioria** [comment]
Hi @slavasav , just to understand.. this is a critical bug that breaks production applications, at least in our experience. Does this mean this library should not be used in production? Chrome has a channel to test upcoming versions before they are released, I assumed this kind of fixes would be released before changes in browsers break applications in production.

If I'm mistaken in my assumptions, and we should be doing things differently, please let me know.
Thanks

**Comment by slavasav** [comment]
Hi, we are fixing the JS sdk right now, expect the release in the next few days.

**Comment by gabro** [comment]
Thanks, that's good news.
Just wondering, is there anything we can do to prevent this from happening in the future?

Thr current sdk is being used in production and right now we're advising our customers to either stick to Chrome 51 or to use the aforementioned workaround, but this is clearly not optimal.

**Comment by slavasav** [comment]
We are working on automating the tests for all the new browser versions, so we can avoid fails like these going forward. Probably nothing you can do on your end, sorry.

**Comment by gabro** [comment]
Ok, thanks for the quick reply! Looking forward to the new SDK release :)

**Comment by slavasav** [comment]
Please use the new 1.4.4 version of the JS sdk available at https://www.sinch.com/downloads/
