### ISSUE TITLE
JSON parse error on client.start

### ISSUE THREAD

**Issue by g0ddish** [sinch/sinch-js-rtc#9]
Hey, I'm trying to start a sinch client with `sinchClient.start({userTicket: response.data.data.signature})` and I've quadruple confirmed that that response.data.data.signature is a valid auth ticket with no special characters in it. (I can post it here if that helps)   However I get a parsing JSON error or similar from the SDK `sinch.min.js:4 SyntaxError: Unexpected token F in JSON at position 0(…)`. 
Anyone have any insight as to why such a simple object is failing to parse and start the client properly?

**Comment by Tantawi** [comment]
Hi,

Can you try again using the latest release and report back?

Thanks!
